services:
  jobmanager:
    build: .
    image: eczachly-pyflink
    container_name: jobmanager
    hostname: jobmanager
    platform: linux/amd64
    env_file:
      - flink-env.env
    expose:
      - "6123"
    ports:
      - "8081:8081"  # Flink Web UI
    volumes:
      - ./:/opt/flink/usrlib
      - ./src/:/opt/src
    command: jobmanager
    networks:
      - shared-net
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_SCHEMA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_SCHEMA}
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager

  taskmanager:
    image: eczachly-pyflink
    container_name: taskmanager
    platform: linux/amd64
    env_file:
      - flink-env.env
    expose:
      - "6121"
      - "6122"
    volumes:
      - ./:/opt/flink/usrlib
      - ./src/:/opt/src
    depends_on:
      - jobmanager
    command: taskmanager --taskmanager.registration.timeout 5 min
    networks:
      - shared-net
    environment:
      FLINK_PROPERTIES: |
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 15
        parallelism.default: 3

networks:
  shared-net:
    external: true
